---
# tasks file for ansible-role-manage_selinux

- name: Install required packages.
  package:
    name:
      - selinux-policy
    state: present
    update_cache: true

- name: Set selinux mode.
  ansible.posix.selinux:
    policy: "{{ mse_policy }}"
    state: "{{ mse_state }}"
